# Generated by Django 5.1.6 on 2025-03-03 22:23

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="is_token_used",
            field=models.BooleanField(default=False, verbose_name="Токен использован"),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(
                help_text="Введите email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
