# Generated by Django 5.1.6 on 2025-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name_course', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description_course', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания курса')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения курса')),
                ('photo_course', models.ImageField(upload_to='courses_photos/', verbose_name='Фото превью')),
                ('video_course', models.CharField(max_length=250, verbose_name='Видео превью')),
                ('pay_course', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name_course'],
            },
        ),
        migrations.CreateModel(
            name='CourseAndStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('course_completion', models.IntegerField(default=0, verbose_name='процент завершения курса')),
                ('finish_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания курса')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name_course_category', models.CharField(max_length=150, unique=True, verbose_name='Категория курса')),
                ('description_course_category', models.TextField(blank=True, null=True, verbose_name='Описание категории курсов')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name_course_category'],
            },
        ),
    ]
