# Generated by Django 5.1.6 on 2025-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='like_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лайки'),
        ),
    ]
